#!/bin/bash

function parse_seconds {
  local seconds="$1"

  local minute=$(( seconds / 60 ))
  local hour=$(( minute / 60 ))
  minute=$(( minute - hour * 60 ))
  local second=$(( seconds % 60 ))

  if [ $hour -lt 10 ]; then hour="0$hour"; fi
  if [ $minute -lt 10 ]; then minute="0$minute"; fi
  if [ $second -lt 10 ]; then second="0$second"; fi

  echo "${hour}:${minute}:${second}"
}

function parse_time {
  local time="$1"
  if [[ ! $time =~ : ]]; then
    echo "$((time * 60 * 60))"
  else
    try=$(echo $time|cut -d ':' -f 3)
    if [ -z "$try" ]; then
      second="00"
    else
      second=$((10#$try))
    fi
    try2=$(echo $time|cut -d ':' -f 2)
    if [ -z "$try2" ]; then
      minute="00"
    else
      minute=$((10#$try2))
    fi
    local hour=$(echo $time|cut -d ':' -f 1)

    hour=$((10#$hour))

    echo $(((hour * 60 + minute) * 60 + second))
  fi
}

function get_bigger {
  local t1="$1"
  local t2="$2"
  local time1=$(parse_time "$t1")
  local time2=$(parse_time "$t2")

  if [ $time1 -lt $time2 ]; then
    echo "$t2 $t1"
  else
    echo "$t1 $t2"
  fi
}

function sub_time {
  local time1=$1
  local time2=$2
  local long_time="$(get_bigger $time1 $time2)"
  local bigger=$(parse_time $(echo $long_time|cut -d' ' -f1))
  local smaller=$(parse_time $(echo $long_time|cut -d' ' -f2))

  local remain=$(( bigger - smaller ))

  echo "$(parse_seconds "${remain}")"
}

if [ $# -ne 2 ]; then
  echo "usage: ${0##*/} [HH:MM:SS] [HH:MM:SS]"
  echo "Subtracts time while preserves formatting"
  exit 2
fi

sub_time $1 $2
